"""init_daily_model

Revision ID: abd33e377ebe
Revises: d5840160257f
Create Date: 2024-09-04 09:01:40.180345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'abd33e377ebe'
down_revision: Union[str, None] = 'd5840160257f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'daily',
        sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column('yesterday_tasks', sa.String(), nullable=False),
        sa.Column('today_plan', sa.String(), nullable=False),
        sa.Column('issues', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily')
    # ### end Alembic commands ###
