name: Test and Check repo

on: [ push, pull_request ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11.x
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Publish code coverage report
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: postgres
          DAILY_MINI_APP_URL: https://asidowner.github.io/dailybot-mini-app/daily-form.html
          DAILY_PLACE: "Some Place"
          DAILY_TIME: 10:15:00+03:00
          BOT_TOKEN: SUPER_SECRET_TOKEN
        with:
          coverageCommand: make test-coverage-report
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
